package com.gaoyh.app.domain;

import java.util.Date;

public class SysConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_config.id
     *
     * @mbggenerated Sun Aug 23 18:05:21 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_config.create_time
     *
     * @mbggenerated Sun Aug 23 18:05:21 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_config.is_deleted
     *
     * @mbggenerated Sun Aug 23 18:05:21 CST 2020
     */
    private Integer deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_config.param_key
     *
     * @mbggenerated Sun Aug 23 18:05:21 CST 2020
     */
    private String paramKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_config.param_name
     *
     * @mbggenerated Sun Aug 23 18:05:21 CST 2020
     */
    private String paramName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_config.param_value
     *
     * @mbggenerated Sun Aug 23 18:05:21 CST 2020
     */
    private String paramValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_config.remark
     *
     * @mbggenerated Sun Aug 23 18:05:21 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_config.update_time
     *
     * @mbggenerated Sun Aug 23 18:05:21 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_config.id
     *
     * @return the value of t_sys_config.id
     *
     * @mbggenerated Sun Aug 23 18:05:21 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_config.id
     *
     * @param id the value for t_sys_config.id
     *
     * @mbggenerated Sun Aug 23 18:05:21 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_config.create_time
     *
     * @return the value of t_sys_config.create_time
     *
     * @mbggenerated Sun Aug 23 18:05:21 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_config.create_time
     *
     * @param createTime the value for t_sys_config.create_time
     *
     * @mbggenerated Sun Aug 23 18:05:21 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_config.is_deleted
     *
     * @return the value of t_sys_config.is_deleted
     *
     * @mbggenerated Sun Aug 23 18:05:21 CST 2020
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_config.is_deleted
     *
     * @param deleted the value for t_sys_config.is_deleted
     *
     * @mbggenerated Sun Aug 23 18:05:21 CST 2020
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_config.param_key
     *
     * @return the value of t_sys_config.param_key
     *
     * @mbggenerated Sun Aug 23 18:05:21 CST 2020
     */
    public String getParamKey() {
        return paramKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_config.param_key
     *
     * @param paramKey the value for t_sys_config.param_key
     *
     * @mbggenerated Sun Aug 23 18:05:21 CST 2020
     */
    public void setParamKey(String paramKey) {
        this.paramKey = paramKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_config.param_name
     *
     * @return the value of t_sys_config.param_name
     *
     * @mbggenerated Sun Aug 23 18:05:21 CST 2020
     */
    public String getParamName() {
        return paramName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_config.param_name
     *
     * @param paramName the value for t_sys_config.param_name
     *
     * @mbggenerated Sun Aug 23 18:05:21 CST 2020
     */
    public void setParamName(String paramName) {
        this.paramName = paramName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_config.param_value
     *
     * @return the value of t_sys_config.param_value
     *
     * @mbggenerated Sun Aug 23 18:05:21 CST 2020
     */
    public String getParamValue() {
        return paramValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_config.param_value
     *
     * @param paramValue the value for t_sys_config.param_value
     *
     * @mbggenerated Sun Aug 23 18:05:21 CST 2020
     */
    public void setParamValue(String paramValue) {
        this.paramValue = paramValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_config.remark
     *
     * @return the value of t_sys_config.remark
     *
     * @mbggenerated Sun Aug 23 18:05:21 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_config.remark
     *
     * @param remark the value for t_sys_config.remark
     *
     * @mbggenerated Sun Aug 23 18:05:21 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_config.update_time
     *
     * @return the value of t_sys_config.update_time
     *
     * @mbggenerated Sun Aug 23 18:05:21 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_config.update_time
     *
     * @param updateTime the value for t_sys_config.update_time
     *
     * @mbggenerated Sun Aug 23 18:05:21 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}