package com.gaoyh.app.mapper;

import java.util.List;

import com.gaoyh.app.domain.SysConfig;

public interface SysConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_config
     *
     * @mbggenerated Sun Aug 23 18:05:21 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_config
     *
     * @mbggenerated Sun Aug 23 18:05:21 CST 2020
     */
    int insert(SysConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_config
     *
     * @mbggenerated Sun Aug 23 18:05:21 CST 2020
     */
    SysConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_config
     *
     * @mbggenerated Sun Aug 23 18:05:21 CST 2020
     */
    List<SysConfig> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_config
     *
     * @mbggenerated Sun Aug 23 18:05:21 CST 2020
     */
    int updateByPrimaryKey(SysConfig record);
}